#Генерация приемов
import telebot
import sqlite3
from random import randint
import log

TOKEN = "430611930:AAFIVPCEvgbf1paCeifOERGUajggAzSlYuQ"
bot = telebot.TeleBot(TOKEN)

def gen_breakfast(message):
    con = sqlite3.connect("C:/Users/mr. Hey/Еда.db")
    cur = con.cursor()
    cur.execute("SELECT COUNT(Завтрак) FROM Завтрак")
    x = cur.fetchone()
    cur.execute("SELECT COUNT(Фрукты) FROM Фрукты")
    y = cur.fetchone()
    cur.execute("SELECT COUNT(Напитки) FROM Напитки")
    z = cur.fetchone()
    a = randint(1, *x)
    b = randint(1, *y)
    c = randint(1, *z)
    cur.execute("SELECT Завтрак FROM Завтрак WHERE id=" + str(a))
    zav = cur.fetchone()
    cur.execute("SELECT Фрукты FROM Фрукты WHERE id=" + str(b))
    fru = cur.fetchone()
    cur.execute("SELECT Напитки FROM Напитки WHERE id=" + str(c))
    nap = cur.fetchone()
    cur.execute("SELECT Ссылка FROM Завтрак WHERE id=" + str(a))
    ss1 = cur.fetchone()
    cur.execute("SELECT Ссылка FROM Напитки WHERE id=" + str(c))
    ss3 = cur.fetchone()
    bot.send_message(message.from_user.id, "1) {}\n2) {}\n3) {}".format(*zav,*nap,*fru))
    con.close()
def gen_lunch(message):
    con = sqlite3.connect("C:/Users/mr. Hey/Еда.db")
    cur = con.cursor()
    cur.execute("SELECT COUNT(Гарнир) FROM Гарнир")
    x = cur.fetchone()
    cur.execute("SELECT COUNT(Мясное) FROM Мясное")
    y = cur.fetchone()
    cur.execute("SELECT COUNT(Овощи) FROM Овощи")
    z = cur.fetchone()
    a = randint(1, *x)
    b = randint(1, *y)
    c = randint(1, *z)
    cur.execute("SELECT Гарнир FROM Гарнир WHERE id=" + str(a))
    garo = cur.fetchone()
    cur.execute("SELECT Мясное FROM Мясное WHERE id=" + str(b))
    meato = cur.fetchone()
    cur.execute("SELECT Овощи FROM Овощи WHERE id=" + str(c))
    ovcho = cur.fetchone()
    cur.execute("SELECT Ссылка FROM Гарнир WHERE id=" + str(a))
    ss1 = cur.fetchone()
    cur.execute("SELECT Ссылка FROM Мясное WHERE id=" + str(b))
    ss2 = cur.fetchone()
    bot.send_message(message.from_user.id, "1) {}\n2){}\n3) {}", format(*garo,*meato,*ovcho))
    con.close()
def gen_dinner(message):
    con = sqlite3.connect("C:/Users/mr. Hey/Еда.db")
    cur = con.cursor()
    cur.execute("SELECT COUNT(Суп) FROM Суп")
    x = cur.fetchone()
    cur.execute("SELECT COUNT(Гарнир) FROM Гарнир")
    y = cur.fetchone()
    cur.execute("SELECT COUNT(Мясное) FROM Мясное")
    z = cur.fetchone()
    cur.execute("SELECT COUNT(Овощи) FROM Овощи")
    w = cur.fetchone()
    a = randint(1, *x)
    b = randint(1, *y)
    c = randint(1, *z)
    d = randint(1, *w)
    cur.execute("SELECT Суп FROM Суп WHERE id=" + str(a))
    sup = cur.fetchone()
    cur.execute("SELECT Гарнир FROM Гарнир WHERE id=" + str(b))
    garu = cur.fetchone()
    cur.execute("SELECT Мясное FROM Мясное WHERE id=" + str(c))
    meatu = cur.fetchone()
    cur.execute("SELECT Овощи FROM Овощи WHERE id=" + str(d))
    ovchu = cur.fetchone()
    cur.execute("SELECT Ссылка FROM Суп WHERE id=" + str(a))
    ss1 = cur.fetchone()
    cur.execute("SELECT Ссылка FROM Гарнир WHERE id=" + str(b))
    ss2 = cur.fetchone()
    cur.execute("SELECT Ссылка FROM Мясное WHERE id=" + str(c))
    ss3 = cur.fetchone()
    bot.send_message(message.from_user.id, "1) {}\n2) {}\n3) {}\n4) {}".format(*sup,*garu,*meatu,*ovchu))
    con.close()
def gen_per(message):
    con = sqlite3.connect("C:/Users/mr. Hey/Еда.db")
    cur = con.cursor()
    cur.execute("SELECT COUNT(Фрукты) FROM Фрукты")
    x = cur.fetchone()
    cur.execute("SELECT COUNT(Сладости) FROM Сладости")
    y = cur.fetchone()
    a = randint(1, *x)
    b = randint(1, *y)
    cur.execute("SELECT Фрукты FROM Фрукты WHERE id=" + str(a))
    fru1 = cur.fetchone()
    cur.execute("SELECT Сладости FROM Сладости WHERE id=" + str(b))
    sla1 = cur.fetchone()
    cur.execute("SELECT Ссылка FROM Завтрак WHERE id=" + str(a))
    ss1 = cur.fetchone()
    bot.send_message(message.from_user.id, "1) {}\n2) {}\n".format(*fru1,*sla1))
    con.close()


